version: "3.9"
services:
  httpserver:
    build: httpserver/.
    expose:
      - "8080"
    ports:
      - "8080:8080"
    tty: true
    
    networks:
      backend:
    volumes:
      - web_data:/usr/data:ro
  
  imed:
    build: imed/.
    depends_on:
      - rabitmq
    networks:
      backend:
    tty: true

  orig:
    build: orig/.
    tty: true
   
    networks:
      backend:

  observ:
    build: observ/.
    tty: true   
    networks:
      backend:
    volumes:
      - web_data:/usr/data
    
  rabitmq:
    image: rabbitmq:3.10-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      backend:
  


networks:
      backend:
volumes:
  web_data:
   

  #sudo docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.10-management
  #https://dev.to/usamaashraf/microservices--rabbitmq-on-docker-e2f
  #https://www.tutorialworks.com/container-networking/
 

 
